version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: data_base
      POSTGRES_USER: sam
    networks:
      - my-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U sam -h db"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - my-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - backend
    volumes:
      - ./frontend:/app
    command: [ "/usr/local/bin/npm", "run", "start"]
    networks:
      - my-network
  
networks:
  my-network:
    driver: bridge